name = "zenbooker-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
account_id = "7e5b73319badf4c429b8018988b72cbb"

[assets]
directory = "src/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
CF_ACCESS_TEAM_DOMAIN = "unclebike"
CF_ACCESS_AUD = "1880df9f2fadb70b7ae5958f76fb9a56240a4171625e379a936868c54b81e3d5"

[[d1_databases]]
binding = "DB"
database_name = "goatkit"
database_id = "7e36e0fb-dc2a-4f02-a6ac-1b292927d8a0"
migrations_dir = "../migrations"

[triggers]
crons = ["0 13 * * *"]
